version: "3.8"

services:
  bot:
    build: .
    container_name: finance-bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_PATH=${DB_PATH}
    volumes:
      - /opt/telegram-bot/data:/app/data
