services:
  bot:
    build: .
    container_name: finance-bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_PATH=/app/data/expenses.db
    volumes:
      - ./data:/app/data
